### ISSUE TITLE
0.13.0 is not marked as latest release on Github

### ISSUE THREAD

**Issue by jinnovation** [kubernetes-el/kubernetes-el#141]
The latest version is 0.13.0 but the corresponding Release in Github is not marked as the latest.

![image](https://user-images.githubusercontent.com/1932579/119355451-47fdac00-bc73-11eb-8c52-7b3abb2e2894.png)

The Releases pane on the repo main page as a result shows the latest release as 0.12.0, i.e. nearly four years ago, which is very misleading to new users. Newcomers would only notice that this is incorrect and there was in fact a more recent release by either:
1. Going into the Releases page
2. Scrolling down to README to look at the MELPA badges.

![image](https://user-images.githubusercontent.com/1932579/119355547-65cb1100-bc73-11eb-8640-df66e087beb5.png)

**Comment by jinnovation** [comment]
[Done.](https://github.com/kubernetes-el/kubernetes-el/releases/tag/0.13.0)

**Comment by noorul** [comment]
@jinnovation How did you do this? I just did a release with ```make release``` and it created 0.14.0 tag but this issue still exists.

**Comment by noorul** [comment]
@jinnovation Ignore it, I drafted a new release manually. May be we need to tweak ```make release```
